name: Flutter Android CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      flutterVersion:
        description: 'Flutter SDK version'
        required: false
        default: '3.19.6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ github.event.inputs.flutterVersion || '3.19.6' }}

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: ${{ runner.os }}-flutter-

      - name: Install Dependencies
        run: |
          flutter pub get
          flutter doctor
        working-directory: budget_simple

      - name: Build Debug APK
        run: flutter build apk --profile
        working-directory: budget_simple

      - name: Upload APK Files
        uses: actions/upload-artifact@v4
        with:
          name: APK Files
          path: budget_simple/build/app/outputs/flutter-apk/app-profile.apk
          retention-days: 14
